name: flutter_template
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_ui_auth: ^1.5.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^9.0.0
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # a tool for running code generators
  build_runner: 2.4.4
  # the code generator
  riverpod_generator: 2.2.3
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: 1.3.2
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: 0.4.0

flutter:
  uses-material-design: true
